### ISSUE TITLE
Stack integration

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-cassandra-client#11]
- [x] initial-work PR
- [x] snapshot publishing
- [x] remove code generation from this project
- [x] integrate with vertx-rx, vertx-lang-js, vertx-lang-groovy, vertx-lang-ruby, vertx-lang-kotlin
- [x] extra doc for vertx-rx
- [x] labelled as tech preview
- [x] integration in vertx-stack project (bom and documentation)
- [x] blog post section for the release blog post that describes the feature and gives an example

**Comment by tsegismont** [comment]
@vietj what do you mean with " integrate with vertx-rx, vertx-lang-js, vertx-lang-groovy, vertx-lang-ruby, vertx-lang-kotlin"

**Comment by tsegismont** [comment]
@vietj I went ahead and pushed PRs to `vertx-dependencies` and `vertx-stack-generation`. I guess this checks the " integrate with vertx-rx, vertx-lang-js, vertx-lang-groovy, vertx-lang-ruby, vertx-lang-kotlin" box

**Comment by vietj** [comment]
vertx-stack-generation does not exist anymore, you need now to do it per repository, i.e in the vertx-rx repo, in the vertx-lang-js- repo, etc...

**Comment by vietj** [comment]
I will delete the vertx-stack-generation repo

**Comment by tsegismont** [comment]
@vietj ok will do. Can you merge https://github.com/vert-x3/vertx-dependencies/pull/16 ?

**Comment by tsegismont** [comment]
@Sammers21 can you take care of "extra doc for vertx-rx"? In the `vertx-rx` repo, there are examples of rxified API for some modules. We should do the same for the Cassandra client.

**Comment by vietj** [comment]
I've completed the `Integration in vertx-stack project (bom and documentation)` item as integrating the generation in various modules break the vertx-stack doc generation

**Comment by tsegismont** [comment]
Thank you Julien

**Comment by Sammers21** [comment]
> @Sammers21 can you take care of "extra doc for vertx-rx"? In the vertx-rx repo, there are examples of rxified API for some modules. We should do the same for the Cassandra client.

Sure

**Comment by Sammers21** [comment]
> blog post section for the release blog post that describes the feature and gives an example

I think I can take care of this as well. But, I guess, we need to create a separated branch and file for the 3.6.0 release first.

**Comment by tsegismont** [comment]
>I think I can take care of this as well. But, I guess, we need to create a separated branch and file for the 3.6.0 release first.

@Sammers21 see my email to vertx-dev, there is a 3.6.0 branch in the Vert.x Website repo now

**Comment by tsegismont** [comment]
Thank you Pavel!
