### ISSUE TITLE
 Implement the cursor API 

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-cassandra-client#2]
We should have the ability to consume results with the cursor API as follows:

```java
cassandraClient.cursor(statement, cursor -> {
    if(cursor.succeeded(){
       cursor.read(50 /* how many rows we'd like to read*/, rows ->{
           if(rows.succeeded()) {
               List<Row> list = rows.result; // here the list of rows is stored
           }
       });
    }
});
```

**Comment by tsegismont** [comment]
@Sammers21 I like the idea, although I wouldn't create a new `Cursor` object, since we already have `ResultSet` which could be enhanced to get a specific number of rows. Do you think this could be contributed to 3.7 ?

**Comment by Sammers21** [comment]
>I wouldn't create a new `Cursor` object, since we already have `ResultSet` which could be enhanced to get a specific number of rows

I agree with this, the feature should be implemented in this way

**Comment by Sammers21** [comment]
> Do you think this could be contributed to 3.7

Yes, I think could be.
