### ISSUE TITLE
3.7 release blog post section

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-cassandra-client#30]
Short description of enhancements brought by the 3.7 release.

https://github.com/vert-x3/vertx-web-site/blob/master/src/site/blog/posts/releases/2019-03-14-vertx-3.7.0-release.md#vertx-cassandra-client

Can you take care of it @Sammers21 ? Thanks

**Comment by Sammers21** [comment]
Yes, i can

**Comment by Sammers21** [comment]
Done in https://github.com/vert-x3/vertx-web-site/commit/d033c8685507a1a56015b0075430d4902fddb9f8
