### ISSUE TITLE
Missing Cassandra Client examples

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-cassandra-client#33]
Stack modules should have a couple of examples in the `vertx-examples` repo.

**Comment by tsegismont** [comment]
@Sammers21 can you take care of this? Thanks

**Comment by Sammers21** [comment]
@tsegismont , sure, will do

**Comment by tsegismont** [comment]
@Sammers21 thank you! Keep it simple, it's not a howto. Code similar to what we have here in tests paired with some comments in Asciidoc would be perfect.
