### ISSUE TITLE
Failed to connect client to cluster

### ISSUE THREAD

**Issue by gadieichhorn** [vert-x3/vertx-cassandra-client#34]
Hi All,

I am testing different startup scenarios that can happen when the client starts and the cluster is not available.

When a client connects to Cassandra and the cluster is not available the connection is valid?

Can I try and execute a command after the cluster is available or do I have to create a new client?

After a connection is lost, will the client try to reconnect? is this configurable?

> com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))

I get this error message on all client calls after the cluster started.

Thanks in advance.

**Comment by tsegismont** [comment]
You shouldn't have to create a new client after the cluster is available.

If the connection is lost, the client should reconnect. You can fine tune the client calling with [`options.dataStaxClusterBuilder()`](https://vertx.io/docs/apidocs/io/vertx/cassandra/CassandraClientOptions.html#dataStaxClusterBuilder--)

**Comment by gadieichhorn** [comment]
Thanks @tsegismont 
Any examples using this options interface? dataStaxClusterBuilder

what will be the typical address format for connecting under docker compose?

```
    CassandraClientOptions options = new CassandraClientOptions()
      .addContactPoint("node1.address")
      .addContactPoint("node2.address")
      .addContactPoint("node3.address");
    CassandraClient client = CassandraClient.createNonShared(vertx, options);
  }
```

I am getting IPv6 exceptions 
>  java.lang.IllegalArgumentException: cassandra-node-0/172.21.0.2:9042: invalid IPv6 address

**Comment by tsegismont** [comment]
>Any examples using this options interface? dataStaxClusterBuilder

```java
    CassandraClientOptions options = new CassandraClientOptions()
      .addContactPoint("node1.address")
      .addContactPoint("node2.address")
      .addContactPoint("node3.address");
    Cluster.Builder clusterBuilder = options.dataStaxClusterBuilder();
    clusterBuilder.withReconnectionPolicy(new ExponentialReconnectionPolicy(1000, 5000));
    CassandraClient client = CassandraClient.createNonShared(vertx, options);
```

>I am getting IPv6 exceptions

What's the format of the contact point string you add to `CassandraOptions`? Can you provide the full stack trace?
The contact point string should be a hostname.

**Comment by gadieichhorn** [comment]
Thanks @tsegismont 
Ok, all works now. thanks for the help
