### ISSUE TITLE
Dynamically change the keyspace on mapper and prepared statment

### ISSUE THREAD

**Issue by gadieichhorn** [vert-x3/vertx-cassandra-client#35]
This is my understanding of Cassandra session so far:
* Sessions are bound to a keyspace.
* PreparedStatments are saved to a keyspace.
* There is no way to provide a keyspace on the mapper on save/get/... dynamically

I wish to create several keyspaces with the same schema so can use the same Cassandra cluster for different "accounts" with the same client connection. Hope this makes sense :)

So far the only way to do this will be to create all statements dynamically (QueryBuilder)? The Builder doesn't support binding for the keyspace :(

I was also thinking of making a prepared statement per keyspace and save to a local map and then use the relevant one for the account. Ugly but may save on performance building query rapidly. 

Appreciate your feedback.

Thanks.

**Comment by tsegismont** [comment]
@gadieichhorn this is by design of the underlying Datastax driver.

I can't think of a better option that what you said (storing keyspace specific objects into local maps)
