### ISSUE TITLE
CassandraRowStream handlers are never called when querying non existent partition

### ISSUE THREAD

**Issue by telecoder** [vert-x3/vertx-cassandra-client#61]
It looks like the CassandraRowStream handlers are never called if you query a non existent partition within a table, thus the query never completes.

### Vertx version

4.0.0.Beta1

### Context

This happens every time a query is made to a table with a non existent partition id. If the test is made with cqlsh it returns an empty result set.

### Do you have a reproducer?

[gist](https://gist.github.com/telecoder/ef1ceda05dd7cca1e28a36ea6cf6af86)

### Cassandra version

4.0-beta1

**Comment by tsegismont** [comment]
@Sammers21 can you please take a look?

**Comment by Sammers21** [comment]
@tsegismont, sure.

**Comment by Sammers21** [comment]
@telecoder, I've tried the reproducer and I'm getting the following output with the "this query never completes" line uncommented:
```Query succeeded```

Problem is that the end handler is never called? Did I get it right?

**Comment by Sammers21** [comment]
@telecoder, I've found out what causes the issue: the order in which you define handlers. 
That is what you do:

```java
rowstream.handler(row -> ...)
         .endHandler(v -> ...)
         .exceptionHandler(e -> ...)
```

It does not work because the `#handler` call performs the emptiness check, and, since there are no rows, he tries to call the `endHandler`, which is not set at the moment. So, in order to fix the problem you have you can simply set handlers in a different order:

```java
rowstream.endHandler(v -> ...)
         .exceptionHandler(e -> ...)
         .handler(row -> ...)
```

The rule is that `#handler` should be the last since it changes stream state: from `IDLE` to `STARTED`

**Comment by Sammers21** [comment]
@tsegismont, I'm not sure if it's a bug. Do you think that we should allow setting the handler in any order or maybe make the documentation more clear?

**Comment by tsegismont** [comment]
@Sammers21 perhaps we could change this:

https://github.com/vert-x3/vertx-cassandra-client/blob/07d179626ae5f8562d5225f223ec2cbcfce73112/src/main/java/io/vertx/cassandra/impl/CassandraRowStreamImpl.java#L82

If we always invoke `runOnContext` then the `endHandler` will be set before the client attempts to fetch any row.

**Comment by telecoder** [comment]
> @telecoder, I've tried the reproducer and I'm getting the following output with the "this query never completes" line uncommented:
> `Query succeeded`
> 
> Ther problem you reporting is that the end handler is never called? Did I get it right?

Yes. I was expecting "Done" to be printed.

> @telecoder, I've found out what causes the issue: the order in which you set handlers.
> That is what you do:
> 
> ```java
> rowstream.handler(row -> ...)
>          .endHandler(v -> ...)
>          .exceptionHandler(e -> ...)
> ```
> 
> It does not work because the `#handler` call performs the emptiness check, and, since there are no rows, he tries to call the `endHandler`, which is not set at the moment. So, in order to fix the problem you have you can simply set handlers in a different order:
> 
> ```java
> rowstream.endHandler(v -> ...)
>          .exceptionHandler(e -> ...)
>          .handler(row -> ...)
> ```
> 
> The rule is that `#handler` should be the last since it changes stream state: from `IDLE` to `STARTED`

Oh, I see.

I have tested the order change and it works. If the declaration order for handlers is that important I agree some comments in the docs could be helpful, but perhaps making the order not relevant at all would be better.

Thanks!

**Comment by Sammers21** [comment]
> vertx-cassandra-client/src/main/java/io/vertx/cassandra/impl/CassandraRowStreamImpl.java

Yes, makes sense.
