### ISSUE TITLE
Paging state should be associated with the row on stream.

### ISSUE THREAD

**Issue by giena** [vert-x3/vertx-cassandra-client#84]
### Version

4.5.7

### Context

I'm trying to get the paging state to persist it, and to be able to restart my application on the last page before failure or a clean stop.
It's a scala projet but i use the vertx promise/future...No interaction withe scala promise/future.

During my tests, i've observed that when there is latency on handler, we get a shift on paging state value.

If my handler goes fast, it's OK.

If my handler goes slow, i've not the same page state for a given row.

It's important, for a given row, to always have the same paging state. Of course the page size is always the same.

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

Her a code snippet:

```scala
findContactsByMailingListStatement.flatMap { stmt =>
      val realStmt = pagingContext.fold {
        stmt.bind(tenantId, listAddress).setPageSize(windowSize)
      } { pagingState =>
        stmt.bind(tenantId, listAddress).setPageSize(windowSize)
          .setPagingState(PagingState.fromString(pagingState.asInstanceOf[String]))
      }
      val ex: Future[CassandraRowStream] = client.queryStream(realStmt)
      ex.onSuccess { stream =>
        logger.debug(s"New row stream $stream")
        FlowableHelper.toFlowable(stream,
          row => {
            val pageState = Option(stream.executionInfo()).flatMap { v => Option(v.getSafePagingState()) }.map(_.toString())
            /*val cbml = unbind(row)
            val contact = cbml.map{c => Contact(c.tenantId, c.contactId, None, None, Map.empty)}*/
            val cbml = unbind(row)
            //println(s"${cbml.map(_.contactId)}/$pageState")
            (unbind(row),pageState)
          }).concatMap { case (cbml,pageState) =>
          AsyncResultSingle.toSingle { (handler:Handler[AsyncResult[(Option[Contact], Option[String])]]) =>
            (cbml.fold {
              logger.warn("Retrieve a null row")
              Future.succeededFuture((Option.empty[Contact],pageState))
            } { cbml =>
              /*contactsDaoImpl.findByPK(cbml.tenantId, cbml.contactId).map {contact =>
                (contact,pageState)
              }*/
              //As the request (findByPK upper) makes me trouble with a cassandra client bad interaction, i prefere
              //make a little latency with a timer
              //If i make a Future.successfull, there is no shift and everything is fine.
              val promise = Promise.promise[(Option[Contact], Option[String])]()
              vertx.setTimer (1, { (_:java.lang.Long) =>
                promise.tryComplete((Option(Contact(cbml.tenantId, cbml.contactId, None, None, Map.empty)), pageState))
              })
              promise.future()
            }).onComplete { r =>
              handler.handle(r)
            }
          }.toFlowable
        }.subscribe ( r => r._1.foreach { contact =>
            handler.handle((contact, ListAddress(listAddress, false), stream, r._2))
          }, t => promise.tryFail(t), () => promise.tryComplete() )
      }

    }
  }

```

  I think it's really a problem.

**Comment by tsegismont** [comment]
I'm not familiar with Scala, perhaps can you post your question to the scala room on the Vert.x Discord server?

**Comment by giena** [comment]
It's not a problem linked on Scala. This problem can occur on Java.

**Comment by tsegismont** [comment]
In this case, can you please provide a small reproducer in Java? Thank you

**Comment by giena** [comment]
I will try to send you an example in Java.
I correct what i thin to be the problem, and here it is the diff based on 4.5.7 (version that i actually use).
https://github.com/vert-x3/vertx-cassandra-client/compare/4.5.7...giena:vertx-cassandra-client:STREAM_EMBED_EXECUTION_INFO?expand=1

If you could have a look on this diff to understand what is the bug.

**Comment by giena** [comment]
Hi @tsegismont ,

I ask a relative question on https://groups.google.com/g/vertx/c/3Ry5YCxqFT4/m/GbHW_YgnBQAJ

Do you know the answer?

Thx.

**Comment by giena** [comment]
Here it is a complete example in Java:

```java
package vertx.cassandra;

import com.datastax.oss.driver.api.core.cql.*;
import com.datastax.oss.driver.api.core.uuid.Uuids;
import io.vertx.core.*;
import io.vertx.cassandra.*;
import io.vertx.rxjava3.FlowableHelper;
import io.vertx.rxjava3.impl.AsyncResultSingle;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class TestFailurePageState {

    //Initialise a vertx instance
    private final Vertx vertx = Vertx.vertx();

    class RowPageState {
        private PagingState pageState;
        private Row row;

        public RowPageState(PagingState pageState, Row row) {
            this.pageState = pageState;
            this.row = row;
        }

        public PagingState getPageState() {
            return pageState;
        }

        public Row getRow() {
            return row;
        }
    }

    public TestFailurePageState() {

    }

    public void initStream() {
        //Initialise a cassandra options with
        //datacenter datacenter1 and keyspace VertxCassandra
        CassandraClientOptions options = new CassandraClientOptions()
                .addContactPoint("localhost", 9042)
                .setKeyspace("VertxCassandra");
        options.dataStaxClusterBuilder().withLocalDatacenter("datacenter1");

        //Initialise a cassandra clien with cassandra options
        CassandraClient client = CassandraClient.createShared(vertx, "MyCassandraClient", options);

        client.execute("DROP TABLE IF EXISTS test_table1").compose(v1 -> {
            return client.execute("DROP TABLE IF EXISTS test_table2").compose(v2 -> {
                return client.execute("CREATE TABLE test_table1 (tenantid varchar, id timeuuid, PRIMARY KEY (tenantid, id))").compose(v3 -> {
                    return client.execute("CREATE TABLE test_table2 (tenantid varchar, id timeuuid, text text, PRIMARY KEY (tenantid, id))");
                });
            });
        }).onComplete(res -> {
            if (res.succeeded()) {
                System.out.println("Tables created");
                //Insert 400 rows with id as timeuuid and text as "Hello World" suffixed by a counter
                Promise<Void> promise = Promise.promise();
                //Prepare a statement for insertion
                client.prepare("INSERT INTO test_table1 (tenantid, id) VALUES ('tenant1', ?)").onSuccess ( resPrepare1 -> {
                    client.prepare("INSERT INTO test_table2 (tenantid, id, text) VALUES ('tenant1', ?, ?)").onSuccess(resPrepare2 -> {
                        insertRow(resPrepare1, resPrepare2, client, 1, promise, 400);
                    }).onFailure(t -> {
                        System.out.println("Prepare failed for test_table2");
                        t.printStackTrace();
                    });
                }).onFailure(t -> {
                    System.out.println("Prepare failed for test_table1");
                    t.printStackTrace();
                });

                //Wait for the insertion to complete
                promise.future().onComplete(ar -> {
                    Future<PreparedStatement> statement2 = client.prepare("SELECT * FROM test_table2 where tenantid='tenant1' and id=?");

                    if (ar.succeeded()) {
                        System.out.println("Insertion completed");

                        //Select all rows using stream with page size 30 using query stream
                        client.queryStream(
                                SimpleStatement.newInstance("SELECT * FROM test_table1 where tenantid='tenant1'").setPageSize(30)
                        ).onSuccess ( stream -> {
                            FlowableHelper.<Row,RowPageState>toFlowable(stream, row -> {
                                PagingState pageState = stream.executionInfo().getSafePagingState();
                                return new RowPageState(pageState, row);
                            }).concatMap(rowPageState -> {
                                return AsyncResultSingle.<Map<String,Object>>toSingle ( handler -> {
                                    enrichRow(client, statement2, rowPageState).onComplete(v -> handleEnrich(handler,v));
                                }).toFlowable();
                            }).subscribe(map -> {
                                System.out.println(map);
                            }, Throwable::printStackTrace, () -> {
                                System.out.println("Stream completed");
                            });
                        }).onFailure ( t -> t.printStackTrace() );
                    } else {
                        ar.cause().printStackTrace();
                    }
                });
            } else {
                System.out.println("Tables creation failed");
                res.cause().printStackTrace();
            }
        });
    }

    //method insertRow to insert a row with id as timeuuid and text as "Hello World" suffixed by a counter
    //make the javadoc comments for the method
    public void insertRow(PreparedStatement statement1, PreparedStatement statement2, CassandraClient client,
                                 int i, Promise<Void> promise, int max) {
        UUID key = Uuids.timeBased();
        client.execute(statement1.bind(key)).compose (v -> {
            return client.execute(statement2.bind(key, "Hello World " + i));
        }).onComplete( res -> {
            if (res.succeeded()) {
                if(i < max) {
                    insertRow(statement1, statement2, client, i + 1, promise, max);
                } else {
                    promise.tryComplete(null);
                }
            } else {
                promise.tryFail(res.cause());
            }
        });
    }

    public Future<Map<String,Object>> enrichRow(CassandraClient client, Future<PreparedStatement> statement2,
                                                       RowPageState rowPageState) {
        String tenantId = rowPageState.getRow().getString("tenantid");
        UUID id = rowPageState.getRow().getUuid("id");
        return statement2.compose( stmt -> {
            return client.execute(stmt.bind(id)).map( res -> {
                Map<String,Object> m = new HashMap<>();
                m.put("tenantid", tenantId);
                m.put("id", id);
                m.put("text", res.one().getString("text"));
                m.put("_pageState_", rowPageState.getPageState());
                return m;
            });
        });
    }

    public void handleEnrich(Handler<AsyncResult<Map<String,Object>>> handler, AsyncResult<Map<String,Object>> ar) {
        handler.handle(ar);
    }

    public static void main(String[] args) {
        System.out.println("TestFailurePageState");
        TestFailurePageState test = new TestFailurePageState();
        test.initStream();
    }
}

```

**Comment by giena** [comment]
With 4.5.7, you will see a transition between the first paging state and the second around the 18th record in the console output:

{_pageState_=001e001000120010c7b3bc80182011ef9b25d7cd9756c443f07fffffe1f07fffffe12b305374e45c8bce63c271c654fce4550005, tenantid=tenant1, id=c7ae8c60-1820-11ef-9b25-d7cd9756c443, text=Hello World 14}
{_pageState_=001e001000120010c7b3bc80182011ef9b25d7cd9756c443f07fffffe1f07fffffe12b305374e45c8bce63c271c654fce4550005, tenantid=tenant1, id=c7af0190-1820-11ef-9b25-d7cd9756c443, text=Hello World 15}
{_pageState_=001e001000120010c7b3bc80182011ef9b25d7cd9756c443f07fffffe1f07fffffe12b305374e45c8bce63c271c654fce4550005, tenantid=tenant1, id=c7af4fb0-1820-11ef-9b25-d7cd9756c443, text=Hello World 16}
{_pageState_=001e001000120010c7b3bc80182011ef9b25d7cd9756c443f07fffffe1f07fffffe12b305374e45c8bce63c271c654fce4550005, tenantid=tenant1, id=c7af9dd0-1820-11ef-9b25-d7cd9756c443, text=Hello World 17}
**{_pageState_=001e001000120010c7b3bc80182011ef9b25d7cd9756c443f07fffffe1f07fffffe12b305374e45c8bce63c271c654fce4550005, tenantid=tenant1, id=c7afebf0-1820-11ef-9b25-d7cd9756c443, text=Hello World 18}
{_pageState_=001e001000120010c7bc4800182011ef9b25d7cd9756c443f07fffffc3f07fffffc343f59688d44e36010e362e0c6e0a6b1d0005, tenantid=tenant1, id=c7b03a10-1820-11ef-9b25-d7cd9756c443, text=Hello World 19}**
{_pageState_=001e001000120010c7bc4800182011ef9b25d7cd9756c443f07fffffc3f07fffffc343f59688d44e36010e362e0c6e0a6b1d0005, tenantid=tenant1, id=c7b08830-1820-11ef-9b25-d7cd9756c443, text=Hello World 20}
{_pageState_=001e001000120010c7bc4800182011ef9b25d7cd9756c443f07fffffc3f07fffffc343f59688d44e36010e362e0c6e0a6b1d0005, tenantid=tenant1, id=c7b0d650-1820-11ef-9b25-d7cd9756c443, text=Hello World 21}
{_pageState_=001e001000120010c7bc4800182011ef9b25d7cd9756c443f07fffffc3f07fffffc343f59688d44e36010e362e0c6e0a6b1d0005, tenantid=tenant1, id=c7b12470-1820-11ef-9b25-d7cd9756c443, text=Hello World 22}
{_pageState_=001e001000120010c7bc4800182011ef9b25d7cd9756c443f07fffffc3f07fffffc343f59688d44e36010e362e0c6e0a6b1d0005, tenantid=tenant1, id=c7b17290-1820-11ef-9b25-d7cd9756c443, text=Hello World 23}

But the pageSize is 30. It seems something is wrong...

With my version (see my diff above):

{_pageState_=001e00100012001093c3e110182111ef987b4fc476603344f07fffffe1f07fffffe12f9f0b6f68e05cf22c31860678e17aa50005, tenantid=tenant1, id=93c2a890-1821-11ef-987b-4fc476603344, text=Hello World 26}
{_pageState_=001e00100012001093c3e110182111ef987b4fc476603344f07fffffe1f07fffffe12f9f0b6f68e05cf22c31860678e17aa50005, tenantid=tenant1, id=93c2f6b0-1821-11ef-987b-4fc476603344, text=Hello World 27}
{_pageState_=001e00100012001093c3e110182111ef987b4fc476603344f07fffffe1f07fffffe12f9f0b6f68e05cf22c31860678e17aa50005, tenantid=tenant1, id=93c344d0-1821-11ef-987b-4fc476603344, text=Hello World 28}
{_pageState_=001e00100012001093c3e110182111ef987b4fc476603344f07fffffe1f07fffffe12f9f0b6f68e05cf22c31860678e17aa50005, tenantid=tenant1, id=93c392f0-1821-11ef-987b-4fc476603344, text=Hello World 29}
**{_pageState_=001e00100012001093c3e110182111ef987b4fc476603344f07fffffe1f07fffffe12f9f0b6f68e05cf22c31860678e17aa50005, tenantid=tenant1, id=93c3e110-1821-11ef-987b-4fc476603344, text=Hello World 30}
{_pageState_=001e00100012001093cbd050182111ef987b4fc476603344f07fffffc3f07fffffc3a4c317f85ead9f27aaecfe81b67bc2480005, tenantid=tenant1, id=93c42f30-1821-11ef-987b-4fc476603344, text=Hello World 31}**
{_pageState_=001e00100012001093cbd050182111ef987b4fc476603344f07fffffc3f07fffffc3a4c317f85ead9f27aaecfe81b67bc2480005, tenantid=tenant1, id=93c47d50-1821-11ef-987b-4fc476603344, text=Hello World 32}
{_pageState_=001e00100012001093cbd050182111ef987b4fc476603344f07fffffc3f07fffffc3a4c317f85ead9f27aaecfe81b67bc2480005, tenantid=tenant1, id=93c4cb70-1821-11ef-987b-4fc476603344, text=Hello World 33}
{_pageState_=001e00100012001093cbd050182111ef987b4fc476603344f07fffffc3f07fffffc3a4c317f85ead9f27aaecfe81b67bc2480005, tenantid=tenant1, id=93c51990-1821-11ef-987b-4fc476603344, text=Hello World 34}

The first transition between two page state is on the 30th record. Like we expect.

But perhaps my use of the rxStream is erroneous or the way i get the paging state too...

Tell me please.

**Comment by giena** [comment]
Hi,

@tsegismont Did you have time to take a look?
Thanks.

**Comment by tsegismont** [comment]
Thank you @giena for all the details and time spent investigating this. I've submitted #85 and will backport to 4.x later

**Comment by tsegismont** [comment]
Closed by 3b5adb8

**Comment by giena** [comment]
Hi @tsegismont,

Do you think the backport will be done soon ?

Thank you.

**Comment by tsegismont** [comment]
Hi @giena , the backport to the `4.x` branch has been made, I assume you're talking about when the 4.5.9 release will be delivered? Usually, unless there's a major problem (i.e CVE) we wait for some time until we get a reasonable amount of fixes.

@vietj do you have any date in mind ATM?
